### ISSUE TITLE
discord

### ISSUE THREAD

**Issue by Nunyabb** [zolantris/ValheimRaft#13]
your invite link is expired. you need to post a perm link on the readme. BTW thanks for resurrecting this mod

**Comment by zolantris** [comment]
Thanks. I'll add it. https://discord.gg/Kcw4d97ez3

**Comment by Nunyabb** [comment]
link is invalid. need to set it to expires "never" 
![Screenshot 2023-12-17 101254](https://github.com/zolantris/ValheimRaft/assets/154016630/1ba4dba8-d1a4-41ca-8a72-b1ee4a301209)
